{
 "title": "ClickHouse (cluster overview)",
 "tags": [
  "PostHog",
  "ClickHouse"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Max node uptime in the cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ClickHouseAsyncMetrics_Uptime{})"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Number of executing queries.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ClickHouseMetrics_Query{})" }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ClickHouseMetrics_VersionInteger)"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (clickhouse_altinity_com_shard) (ClickHouseMetrics_VersionInteger))"
    }
   ]
  },
  {
   "title": "Nodes count",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count(ClickHouseMetrics_VersionInteger)",
     "legendFormat": "Nodes count"
    }
   ]
  },
  {
   "title": "Nodes uptime",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_Uptime{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "description": "Number of executing queries.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_Query{}", "legendFormat": "{{pod}}" },
    { "expr": "sum(ClickHouseMetrics_Query{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed queries",
   "type": "timeseries",
   "description": "Number of failed queries.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseProfileEvents_FailedQuery{}",
     "legendFormat": "{{pod}}"
    },
    { "expr": "sum(ClickHouseMetrics_Query{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Slow reads",
   "type": "timeseries",
   "description": "Number of reads from a file that were slow. This indicate system overload.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SlowRead{}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read backoff",
   "type": "timeseries",
   "description": "Number of times the number of query processing threads was lowered due to slow reads.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_ReadBackoff{}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Number of connections to TCP server (clients with native interface), also included server-server distributed query connections & number of connections to HTTP server",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection",
     "legendFormat": "TCP - {{pod}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "HTTP - {{pod}}"
    }
   ]
  },
  {
   "title": "Replication queue size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasMaxQueueSize{}",
     "legendFormat": "Max queue - {{pod}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_ReplicasSumQueueSize{}",
     "legendFormat": "Sum queue - {{pod}}"
    }
   ]
  },
  {
   "title": "SELECT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SELECT queries",
   "type": "timeseries",
   "description": "Number of executing SELECT ueries.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_SelectQuery{}[$interval])",
     "legendFormat": "{{pod}}"
    },
    { "expr": "sum(ClickHouseMetrics_Query{})", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed SELECT queries",
   "type": "timeseries",
   "description": "Number of failed SELECT queries.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseProfileEvents_FailedSelectQuery{}[$interval])",
     "legendFormat": "{{pod}}"
    },
    { "expr": "sum(ClickHouseMetrics_Query{})", "legendFormat": "Total" }
   ]
  }
 ]
}