{
 "title": "Django views",
 "tags": [
  "PostHog",
  "Django"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "view",
    "query": {
     "query": "label_values(django_http_requests_latency_seconds_by_view_method_bucket{}, view)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(django_http_requests_total_by_view_transport_method_total{view=\"$view\"}[$__interval]))",
     "legendFormat": "Http requests"
    }
   ]
  },
  {
   "title": "HTTP responses by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(status) (increase(django_http_responses_total_by_status_view_method_total{view=\"$view\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(django_http_exceptions_total_by_view_total{view=\"$view\"}[$__interval]))",
     "legendFormat": "Error count"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    django_http_requests_latency_seconds_by_view_method_bucket{view=\"$view\"}[5m]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view=\"$view\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view=\"$view\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view=\"$view\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    }
   ]
  }
 ]
}