{
 "title": "PgBouncer",
 "tags": [
  "PostHog",
  "pgbouncer"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_pooled_total{}[5m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Query time (p50)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_queries_duration_seconds_total{}[5m])) /\nsum(rate(pgbouncer_stats_queries_pooled_total{}[5m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Client connections used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(pgbouncer_used_clients) / (sum(pgbouncer_used_clients) + sum(pgbouncer_free_clients)) ",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Servers connections used",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(pgbouncer_used_servers) / (sum(pgbouncer_used_servers) + sum(pgbouncer_free_servers)) ",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Pod(s) count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count(pgbouncer_version_info{})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Client connections by state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_active_connections)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(pgbouncer_pools_client_waiting_connections)",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Server connections by state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_server_active_connections)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(pgbouncer_pools_server_idle_connections)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(pgbouncer_pools_server_used_connections)",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "by pod(s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(pod)(rate(pgbouncer_stats_sql_transactions_pooled_total{}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Client connections used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "targets": [
    { "expr": "pgbouncer_used_clients", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Server connections used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "pgbouncer_used_servers", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}