{
 "title": "Session recordings",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "posthog-plugins-ingestion replica status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"posthog\", deployment=\"posthog-plugins-ingestion\"})",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"posthog\",deployment=\"posthog-plugins-ingestion\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"posthog\",deployment=\"posthog-plugins-ingestion\"})",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "Message byte size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(consumed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Message batch size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(consumed_batch_size_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Topic production/consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{topic=\"session_recording_events\"}[5m])/5)",
     "legendFormat": "produced"
    },
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{topic=\"session_recording_events\", consumergroup=\"session-recordings\"}[5m])/5)",
     "legendFormat": "consumed"
    }
   ]
  },
  {
   "title": "Consumer group lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"session_recording_events\", consumergroup=\"session-recordings\"})",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Consumption time lag seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(time() * 1000 - (max(latest_processed_timestamp_ms{groupId=\"session-recordings\",topic=\"session_recording_events\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container=\"posthog-plugins-ingestion\"} | json"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "posthog-events replica status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=\"posthog\", deployment=\"posthog-events\"})",
     "legendFormat": "updated"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"posthog\",deployment=\"posthog-events\"})",
     "legendFormat": "available"
    },
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=\"posthog\",deployment=\"posthog-events\"})",
     "legendFormat": "unavailable"
    }
   ]
  },
  {
   "title": "/s/ success rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{status!~\"5.*\", path=~\"/s/?\"}[2m]\n      )\n   )\n/ \n\nsum(\n  rate(\n    nginx_ingress_controller_requests{path=~\"/s/?\"}[2m]\n      )\n    )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "/s/ requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{path=\"/e/\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NGINX logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"} |= `POST /s/` | json"
    }
   ]
  }
 ]
}