#
# AWS resizable disk example
#
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-resizable
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
#volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "posthog"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volumeclaim-template
  configuration:
    users:
      admin/password: a1f31e03-c88e-4ca6-a2df-ad49183d15d9
      admin/networks/ip: "0.0.0.0/0"
      admin/profile: default
      admin/quota: default
      default/password: a1f31e03-c88e-4ca6-a2df-ad49183d15d9
      default/networks/ip: "0.0.0.0/0"
    clusters:
      - name: "posthog"
        templates:
          podTemplate: pod-template-with-volumes
        layout:
          shardsCount: 1
          replicasCount: 1
    settings:
      format_schema_path: /etc/clickhouse-server/config.d/
    files:
      events.proto: |
        syntax = "proto3";
        message Event {
          string uuid = 1;
          string event = 2;
          string properties = 3;
          string timestamp = 4;
          uint64 team_id = 5;
          string distinct_id = 6;
          string created_at = 7;
          string elements_chain = 8;
        }
  templates:
    podTemplates:
      - name: pod-template-with-volumes
        spec:
          containers:
            - name: clickhouse
              image: yandex/clickhouse-server:20.10.3.30
              ports:
                - name: http
                  containerPort: 8123
                - name: client
                  containerPort: 9000
                - name: interserver
                  containerPort: 9009
              volumeMounts:
                - name: data-volumeclaim-template
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "8Gi"
                  cpu: "2"
                limits:
                  memory: "16Gi"
                  cpu: "4"
    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: gp2-resizable
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2000Gi
