# Used in https://github.com/digitalocean/marketplace-kubernetes/tree/master/stacks/posthog
cloud: "do"
deploymentType: "DigitalOcean 1-click"
ingress:
  nginx:
    enabled: true
    redirectToTLS: false
  letsencrypt: false
web:
  secureCookies: false
