{{- if .Values.beat.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "posthog.fullname" . }}-beat
  labels:
    app: {{ template "posthog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "posthog.fullname" . }}-beat
  minReplicas: {{ .Values.beat.hpa.minpods }}
  maxReplicas: {{ .Values.beat.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.beat.hpa.cputhreshold }}
{{- end }}
