{{- if .Values.clickhouseOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clickhouse-operator
  namespace: {{ .Values.clickhouseOperator.namespace | default .Release.Namespace }}
{{- end }}
