{{- if .Values.clickhouse.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup-cron
spec:
  schedule: {{ .Values.clickhouse.backup.backup_schedule | quote }}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      backoffLimit: 1
      completions: 1
      parallelism: 1
      template:
        metadata:
          labels:
            job: clickhouse-backup
        spec:
          restartPolicy: Never
          containers:
            - name: run-backup-cron
              image: {{ template "client.clickhouse.image" . }}
              imagePullPolicy: IfNotPresent
              env:
                - name: CLICKHOUSE_SERVICES
                  value: {{ .Values.clickhouse.backup.clickhouse_services }}
                - name: CLICKHOUSE_PORT
                  value: "9000"
                - name: BACKUP_USER
                  value: {{ .Values.clickhouse.backup.backup_user }}
                - name: BACKUP_PASSWORD
                  value: {{ .Values.clickhouse.backup.backup_password }}
              command: ["/bin/sh", "-c", "/scripts/backup_script.sh"]
              volumeMounts:
              - name: clickhouse-backup-script
                mountPath: /scripts/backup_script.sh
                subPath: backup_script.sh
          volumes:
          - name: clickhouse-backup-script
            configMap:
              name: clickhouse-backup-script
              defaultMode: 0777
{{- end }}