{{- if .Values.clickhouse.enabled }}
{{- if .Values.clickhouse.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "posthog.clickhouse.serviceAccount" . }}
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  {{- if .Values.clickhouse.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.clickhouse.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
