{{- if .Values.clickhouse.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-backup-script
data:
{{ (.Files.Glob "scripts/backup_script.sh").AsConfig | indent 2 }}
{{- end }}