
{{- if and .Values.ingress.enabled (eq (include "ingress.type" .) "clb")  -}}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: "{{ .Release.Name }}-frontend-config"
spec:
  redirectToHttps:
    enabled: {{ .Values.ingress.gcp.forceHttps }}
{{- end -}}
