{{- if (and .Values.ingress.gcp (eq (include "ingress.type" .) "clb")) -}}
{{- if (.Values.ingress.gcp.ip_name) -}}
{{- if not (.Values.ingress.gcp.secretName) }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: "{{ .Release.Name }}-gke-cert"
spec:
  domains:
    - {{ .Values.ingress.hostname }}
{{- end -}}
{{- end -}}
{{- end -}}

