{{- if .Values.kafka.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "posthog.fullname" . }}-kafka
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
{{- if .Values.kafka.service.labels }}
{{ toYaml .Values.kafka.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ default "9092" .Values.kafka.port }}
    targetPort: {{ default "9092" .Values.kafka.port }}
    protocol: TCP
    name: kafka
  selector:
    app: {{ template "posthog.fullname" . }}
    release: {{ .Release.Name }}
    role: kafka
{{- end }}
