{{ if .Values.pluginsIngestion.enabled }}
{{/* 
    A deployment for "overflow" events using pluginsIngestion settings unless
    they are overriden by pluginsIngestionOverflow
*/}}
{{ 
    include "plugins-deployment" ( dict "root" . "params" (
        merge .Values.pluginsIngestionOverflow (omit .Values.pluginsIngestion "hpa")
    ) "name" "plugins-ingestion-overflow" "mode" "ingestion-overflow" ) }}
{{ end }}
