{{- if and .Values.pluginsAsync.enabled .Values.pluginsAsync.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "posthog.fullname" . }}-plugins-async
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "posthog.fullname" . }}-plugins-async
  {{ if .Values.plugins.autoscaling }}
  {{ .Values.plugins.autoscaling | nindent 2 }}
  {{ else }}
  minReplicas: {{ .Values.plugins.hpa.minpods }}
  maxReplicas: {{ .Values.plugins.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.plugins.hpa.cputhreshold }}
  {{ end }}
{{- end }}
