{{- if (include "posthog.postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "posthog.postgresql.secretName" . }}
type: Opaque
data:
  {{ template "posthog.postgresql.secretPasswordKey" . }}: {{ .Values.externalPostgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
