{{- if .Values.temporal_python_worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "posthog.fullname" . }}-temporal-python-worker
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
  annotations: {{- include "_snippet-metadata-annotations-common" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: {{ template "posthog.fullname" . }}
        release: "{{ .Release.Name }}"
        role: temporal-python-worker 
  {{- if not .Values.temporal_python_worker.hpa.enabled }}
  replicas: {{ .Values.temporal_python_worker.replicacount }}
  {{- end }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.temporal_python_worker.rollout.maxSurge }}
      maxUnavailable: {{ .Values.temporal_python_worker.rollout.maxUnavailable }}

  template:
    metadata:
      annotations:
        checksum/secrets.yaml: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- if .Values.temporal_python_worker.podAnnotations }}
{{ toYaml .Values.temporal_python_worker.podAnnotations | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "posthog.fullname" . }}
        release: "{{ .Release.Name }}"
        role: temporal-python-worker
        {{- if (eq (default .Values.image.tag "none") "latest") }}
        date: "{{ now | unixEpoch }}"
        {{- end }}
        {{- if .Values.temporal_python_worker.podLabels }}
{{ toYaml .Values.temporal_python_worker.podLabels | indent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ include "snippet.temporal_python_worker-deployments.terminationGracePeriodSeconds" . }}
      serviceAccountName: {{ template "posthog.serviceAccountName" . }}

      {{- if .Values.temporal_python_worker.affinity }}
      affinity:
{{ toYaml .Values.temporal_python_worker.affinity | indent 8 }}
      {{- end }}

      {{- if .Values.temporal_python_worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.temporal_python_worker.nodeSelector | indent 8 }}
      {{- end }}

      {{- if .Values.temporal_python_worker.tolerations }}
      tolerations:
{{ toYaml .Values.temporal_python_worker.tolerations | indent 8 }}
      {{- end }}

      {{- if .Values.temporal_python_worker.schedulerName }}
      schedulerName: "{{ .Values.temporal_python_worker.schedulerName }}"
      {{- end }}

      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}

      # I do not know for sure if the old one has been used anywhere, so do both :(
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      {{- if .Values.temporal_python_worker.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.temporal_python_worker.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}-temporal_python_worker
        image: {{ template "posthog.image.fullPath" . }}
        command:
          - ./bin/temporal-django-worker
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        # Expose the port on which Prometheus /metrics endpoint resides
        - containerPort: 8001
        env:
        # Common settings 
        {{- include "snippet.kafka-env" . | indent 8 }}
        {{- include "snippet.objectstorage-env" . | indent 8 }}
        {{- include "snippet.redis-env" . | indent 8 }}
        {{- include "snippet.statsd-env" . | indent 8 }}

        # PostHog app settings
        {{- include "snippet.posthog-env" . | indent 8 }}
        {{- include "snippet.posthog-sentry-env" . | indent 8 }}
        - name: PRIMARY_DB
          value: clickhouse
        {{- include "snippet.postgresql-env" . | nindent 8 }}
        {{- include "snippet.clickhouse-env" . | nindent 8 }}
        {{- include "snippet.email-env" . | nindent 8 }}
{{- if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
{{- end }}
{{- if .Values.temporal_python_worker.env }}
{{ toYaml .Values.temporal_python_worker.env | indent 8 }}
{{- end }}
      initContainers:
      {{- include "_snippet-initContainers-wait-for-service-dependencies" . | indent 8 }}
      {{- include "_snippet-initContainers-wait-for-migrations" . | indent 8 }}
{{- end }}
