{{- if and .Values.web.enabled .Values.web.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "posthog.fullname" . }}-web
  labels: {{- include "_snippet-metadata-labels-common" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "posthog.fullname" . }}-web
  minReplicas: {{ .Values.web.hpa.minpods }}
  maxReplicas: {{ .Values.web.hpa.maxpods }}
  targetCPUUtilizationPercentage: {{ .Values.web.hpa.cputhreshold }}
{{- end }}
