cloud: "do"

ingress:
  enabled: false

service:
  externalPort: 80

image:
  repository: ghcr.io/posthog/posthog/posthog
  pullPolicy: Always
  tag: pr-14915

env:
- name: bump
  value: "2"
- name: SELF_CAPTURE
  value: "1"
- name: PERSISTED_FEATURE_FLAGS
  value: "hogql"

siteUrl: https://posthog-databeach.hedgehog-kitefin.ts.net
tailscale:
  enabled: true
  hostname: posthog-databeach

clickhouse:
  persistence:
    size: 100Gi

kafka:
  persistence:
    size: 1Gi

postgresql:
  persistence:
    size: 10Gi
  primary:
    nodeSelector:
      kubernetes.io/arch: amd64

redis:
  master:
    persistence:
      size: 1Gi

zookeeper:
  persistence:
    size: 1Gi

  nodeSelector:
    kubernetes.io/arch: amd64


