contact_links:
  - name: "\U0001F914 All other questions, including if you're not sure what to do."
    url: https://posthog.com/questions
    about: Search on our community for similar questions or ask for help there.
