cloud: private

# Expose
ingress:
  enabled: true
  nginx:
    enabled: true
    redirectToTLS: false

ingress-nginx:
  controller:
    service:
      nodePorts:
        http: 30003

grafana:
  enabled: true

  service:
    enabled: true
    type: NodePort
    nodePort: 30000

  grafana.ini:
    # Disable auth for local testing
    auth:
      disable_login_form: true

    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin

prometheus:
  enabled: true

  server:
    service:
      type: NodePort
      nodePort: 30001

  alertmanager:
    enabled: true

    service:
      type: NodePort
      nodePort: 30002

loki:
  enabled: true

  minio:
    enabled: true

    persistence:
      size: 1Gi

    consoleService:
      type: NodePort
      nodePort: 30005

eventrouter:
  enabled: true

promtail:
  enabled: true

prometheus-postgres-exporter:
  enabled: true

prometheus-kafka-exporter:
  enabled: true

prometheus-redis-exporter:
  enabled: true
