{{- if .Values.clickhouse.enabled }}
# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clickhouse-operator-{{ .Values.clickhouse.namespace | default .Release.Namespace }}
  namespace: {{ .Values.clickhouse.namespace | default .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: 0.18.4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator-{{ .Values.clickhouse.namespace | default .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: clickhouse-operator
  namespace: {{ .Values.clickhouse.namespace | default .Release.Namespace }}

{{- end }}
