#
# GitHub Action to automate the identification of common misspellings in text files.
# - https://github.com/codespell-project/actions-codespell
# - https://github.com/codespell-project/codespell
#
name: Codespell
on: [pull_request]
jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Codespell
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          check_hidden: true
          # Don't check the .git folder as well as few files that we get from upstream
          skip: .git,./charts/posthog/crds/clickhouse_installation.yaml,./charts/posthog/templates/clickhouse_config_map.yaml
