name: Lint test

on: push

jobs:
  helm-lint:
    name: helm lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cloud: ["aws", "azure", "do", "gcp", "other"]
    steps:
      - uses: actions/checkout@v2
      - run: helm lint --set "cloud=${{ matrix.cloud }}" charts/posthog
