name: Lint test

on: push

jobs:
  helm-lint:
    name: helm lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cloud: ["aws", "azure", "do", "gcp", "other"]
    steps:
      - uses: actions/checkout@v2
      - run: helm lint --strict --set "cloud=${{ matrix.cloud }}" charts/posthog

  eslint:
    name: ESLint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
