# This workflow handles deploying a branch to the pull request cluster, for
# testing purposes. It is locked down so that it can only be used by people who
# are a member of the PostHog Github org

name: PR - Preview Deploy

on:
  pull_request:
    types: 
      - labeled
      - synchronize

jobs:
  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@17f29510f1bf987b916c8cbb451566a56eed23f1
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2 # no way of getting the correct ref from the issue event, hence the below
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 

      - name: Declare variables that we can share across steps
        id: vars
        run: |
          GIT_SHORT="$(git rev-parse --short HEAD)"
          PR_NUM=${{ github.event.number }}

          echo "::set-output name=git_short::${GIT_SHORT}"
          echo "::set-output name=fqdn_record::${PR_NUM}.pr.posthog.cc"
          echo "::set-output name=pr_number::${PR_NUM}"
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.head_ref }}
          ref: ${{ github.head_ref }}
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 

      - name: Install doctl to access k8s config
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 

      - name: Install PostHog using the Helm chart
        id: helm_install
        run: |
          doctl kubernetes cluster kubeconfig save $PR_CLUSTER_ID 

          helm upgrade --install \
            -f ci/values/pr/values.yaml \
            --set ingress.hostname=${{ steps.vars.outputs.fqdn_record }} \
            --timeout 30m \
            --create-namespace \
            --namespace pr-${{ steps.vars.outputs.pr_number }} \
            posthog ./charts/posthog \
            --wait \
            --wait-for-jobs 
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 
        env:
          PR_CLUSTER_ID: ${{ secrets.PR_CLUSTER_ID }} # probably not _SECRET_, but best kept out of the YAML

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          ref: ${{ github.head_ref }}
          env_url: https://${{ steps.vars.outputs.fqdn_record }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        if: ${{ steps.check.outputs.has-permission && contains(github.event.pull_request.labels.*.name, 'deploy') }} 

