name: Lint test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - charts/**
      - .github/workflows/test-lint-helm.yaml
  push:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cloud: ["aws", "azure", "do", "gcp", "other"]
    steps:
      - uses: actions/checkout@v3
      - run: helm lint --strict --set "cloud=${{ matrix.cloud }}" charts/posthog

    # Cancel pending and in-progress runs of this workflow if a newer ref is pushed to CI.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
