name: Lint test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/**
  push:
    branches:
      - main

jobs:
  github-workflows-lint:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download actionlint
        env:
          ACTIONLINT_VERSION: 1.6.8
        run: wget -q -O- "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz" | tar -x -z -C . actionlint

      - name: Run actionlint
        run: ./actionlint -color -ignore shellcheck
