name: e2e - k3s

on:
  workflow_dispatch:
  push:
    paths:
      - ci/**
      - charts/**
      - .github/workflows/test-helm-chart.yaml

jobs:
  test-chart:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        # We run this job multiple times with different parameterization
        # specified below, these parameters have no meaning on their own and
        # gain meaning on how job steps use them.
        include:
          - k3s-channel: v1.23
            test: install
          - k3s-channel: v1.22
            test: install
          - k3s-channel: v1.21
            test: install
          - k3s-channel: v1.20
            test: install

          # We run an upgrade test where we first install an already released
          # Helm chart version and then upgrade to the version we are now
          # testing. We test upgrading from the latest main version.
          #
          # It can be very useful to see the "Helm diff" step's output from the
          # latest dev version.
          - k3s-channel: v1.21
            test: upgrade

    steps:
      - uses: actions/checkout@v2

      # Starts a k8s cluster with NetworkPolicy enforcement and installs both
      # kubectl and helm
      #
      # ref: https://github.com/jupyterhub/action-k3s-helm/
      - uses: jupyterhub/action-k3s-helm@v1
        with:
          k3s-channel: ${{ matrix.k3s-channel }}
          metrics-enabled: false
          traefik-enabled: false

      - uses: actions/checkout@v2
        if: matrix.test == 'upgrade'
        with:
          ref: main
          path: main

      - name: (Upgrade) Install our helm chart from main branch
        if: matrix.test == 'upgrade'
        run: |
          helm upgrade --install -f ci/values/k3s.yaml --timeout 20m --create-namespace --namespace posthog posthog ./main/charts/posthog --wait --wait-for-jobs --debug

      - name: "(Upgrade) Install helm diff"
        if: matrix.test == 'upgrade'
        run: |
          helm plugin install https://github.com/databus23/helm-diff --version 3.1.3

      - name: "(Upgrade) Helm diff ${{ matrix.upgrade-from }} chart with local chart"
        if: matrix.test == 'upgrade'
        run: |
          helm diff upgrade --install -f ci/values/k3s.yaml --namespace posthog posthog ./charts/posthog --debug

      - name: "(Upgrade) Await chart install"
        if: matrix.test == 'upgrade'
        uses: jupyterhub/action-k8s-await-workloads@main
        with:
          namespace: "posthog"
          timeout: 300
          max-restarts: 10

      - name: Install our helm chart
        run: |
          helm upgrade --debug --install -f ci/values/k3s.yaml --timeout 20m --create-namespace --namespace posthog posthog ./charts/posthog --wait --wait-for-jobs --debug

      #
      # Wait for all k8s resources to be ready.
      #
      # Despite the --wait flag used in the command above
      # there is no guarantee that all the resources will be deployed
      # when the command returns.
      #
      #
      # Why can't we directly use the 'action-k8s-await-workloads' step below?
      # Because it's not working for this use case
      #
      # ref: https://github.com/jupyterhub/action-k8s-await-workloads/issues/38
      #
      - name: Workaround - wait for all the k8s resources to be ready
        timeout-minutes: 15
        run: |
          echo "Waiting for jobs to be ready..."
          while ! kubectl -n posthog wait --for=condition=Complete jobs --all --timeout 10s > /dev/null 2>&1
          do
            sleep 1
          done
          echo "All jobs are now ready!"

          echo "Waiting for all deployments to be ready..."
          for deployment in $(kubectl -n posthog get deployments --no-headers -o custom-columns=NAME:.metadata.name)
          do
            while ! kubectl -n posthog rollout status deployment "$deployment" > /dev/null 2>&1
            do
              sleep 1
            done
          done
          echo "All deployments are now ready!"

      - name: Wait until all the resources are fully deployed in k8s
        uses: jupyterhub/action-k8s-await-workloads@main
        with:
          namespace: "posthog"
          timeout: 300
          max-restarts: 10

      - name: Setup PostHog for the ingestion test
        run: ./ci/setup_ingestion_test.sh

      - name: Set PostHog endpoints to use for the ingestion test
        run: |
          POSTHOG_API_ADDRESS=$(kubectl get svc -n posthog posthog-web -o jsonpath="{.spec.clusterIP}")
          POSTHOG_EVENTS_ADDRESS=$(kubectl get svc -n posthog posthog-events -o jsonpath="{.spec.clusterIP}")

          echo "POSTHOG_API_ENDPOINT=http://${POSTHOG_API_ADDRESS}:8000" | tee -a "$GITHUB_ENV"
          echo "POSTHOG_EVENT_ENDPOINT=http://${POSTHOG_EVENTS_ADDRESS}:8000" | tee -a "$GITHUB_ENV"

          # Skip the source ip address check in ingestion-test.js
          echo "SKIP_SOURCE_IP_ADDRESS_CHECK=true" | tee -a "$GITHUB_ENV"

      - name: Run ingestion test using k6
        uses: k6io/action@v0.2.0
        with:
          filename: ci/k6/ingestion-test.js

      # GitHub Action reference: https://github.com/jupyterhub/action-k8s-namespace-report
      - name: Emit namespace report
        uses: jupyterhub/action-k8s-namespace-report@v1
        if: always()
        with:
          namespace: posthog
