name: Lint test

on:
  workflow_dispatch:
  push:
    paths:
      - 'ci/kubetest/**'
      - .github/workflows/test-lint-flake8.yaml

jobs:
  kubetest:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python dependencies
        run: |
          python -m pip install -r ci/kubetest/requirements.txt

      - name: Check formatting
        run: |
          black --check ci/kubetest
          isort --check-only ci/kubetest

      - name: Lint with flake8
        run: |
          flake8 --config ci/kubetest/.flake8 ci/kubetest
