name: Lint test

on:
  workflow_dispatch:
  push:
    paths:
      - charts/**
      - .github/workflows/test-lint-helm.yaml

jobs:
  helm-lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cloud: ["aws", "azure", "do", "gcp", "other"]
    steps:
      - uses: actions/checkout@v3
      - run: helm lint --strict --set "cloud=${{ matrix.cloud }}" charts/posthog
