name: e2e - kubetest (store test durations)

on:
  schedule:
    - cron: '0 4 * * 1-5' # Mon-Fri 4AM UTC
  workflow_dispatch: {}

jobs:
  test-kubetest-store-durations:
    runs-on: ubuntu-20.04
    timeout-minutes: 3600
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: jupyterhub/action-k3s-helm@v2
        with:
          k3s-channel: v1.22
          metrics-enabled: false
          traefik-enabled: false

      - name: Install Python dependencies
        run: |
          python -m pip install -r ci/kubetest/requirements.txt

      - name: Run kubetest
        run: |
          cd ci/kubetest && python -m pytest . -s --store-durations

      - name: Save test durations
        if: ${{ github.repository == 'PostHog/charts-clickhouse' && github.ref == 'refs/heads/main' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: 'Save test durations'
            commit_user_name: PostHog Bot
            commit_user_email: hey@posthog.com
            commit_author: PostHog Bot <hey@posthog.com>
