name: Update docs

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Run helm-docs
        run: |
          GOBIN=$PWD go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.8.1
          ./helm-docs --sort-values-order file -t ALL_VALUES.md.gotmpl -o ALL_VALUES.md
          rm ./helm-docs

      - name: Commit bump
        uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02 # v7.5.0
        with:
            author_name: Max Hedgehog
            author_email: 127861667+max-hedgehog[bot]@users.noreply.github.com
            branch: ${{ github.event.pull_request.base.ref }}
            message: 'Regenerate chart ALL_VALUES.md'
